### ISSUE TITLE
teamcity-surge-autorelease breaks usage outside of Wix

### ISSUE THREAD

**Issue by barakplasma** [wix/wix-animations#5]
When I try to use the latest version of Wix Style React, I cannot since wix-animations depends on  teamcity-surge-autorelease which breaks usage outside of Wix 

> error An unexpected error occurred: "Couldn't find package \"teamcity-surge-autorelease@^1.0.9\" required by \"wix-animations@^1.0.141\" on the \"npm\" registry.".

The failure occurred during the following command

`$ yarn add wix-style-react@4.9.0 --ignore-scripts --no-lockfile --non-interactive --no-bin-links --ignore-engines --skip-integrity-check`

Here is an example of the error:
https://codesandbox.io/s/3vk67mvo6

This issue relates to https://github.com/wix/wix-ui/issues/524 which was solved via https://github.com/wix/wix-ui/pull/558

**Comment by barakplasma** [comment]
relates to https://github.com/wix/wix-animations/blob/c7e193848417ad5adda210861276a670179dba82/package.json#L72-L75

**Comment by shlomitc** [comment]
should be fixed now
https://github.com/wix/wix-animations/commit/8985a7dfd599407f5cb338be8fc560e4a9b4f85e

**Comment by barakplasma** [comment]
Thanks!
